# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAok2HJyQ4duL9i_Llkh6_tmRd_aSjI5
"""

scores = input().split()
fail_count = sum(1 for s in scores if int(s) < 60)
print(fail_count)
average = sum(int(s) for s in scores) / len(scores)
print(f"{average:.2f}")