# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/149_9KHbkpI4MNIxOJMT5xoWuJxkm38Z8
"""

scores = list(map(int, input().split()))

fail_count = sum(1 for s in scores if s < 60)
max_score = max(scores)
min_score = min(scores)
print(fail_count)
print(max_score)
print(min_score)

scores = list(map(int, input().split()))
print()